// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhI8pQqT4w20q-x4bOnOl_4CMotYWaEqc',
    appId: '1:347110904414:web:78b7cf505b7cf991cc9acf',
    messagingSenderId: '347110904414',
    projectId: 'greentechfertilizer-b5cd0',
    authDomain: 'greentechfertilizer-b5cd0.firebaseapp.com',
    databaseURL: 'https://greentechfertilizer-b5cd0-default-rtdb.firebaseio.com',
    storageBucket: 'greentechfertilizer-b5cd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG0Key3spkyyloK-XVc0Pt8A-Z_kZmhfs',
    appId: '1:347110904414:android:5e2be68a65835bddcc9acf',
    messagingSenderId: '347110904414',
    projectId: 'greentechfertilizer-b5cd0',
    databaseURL: 'https://greentechfertilizer-b5cd0-default-rtdb.firebaseio.com',
    storageBucket: 'greentechfertilizer-b5cd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8eaMkb0ePV0rJnKLIogWNAmzsyr-9Boc',
    appId: '1:347110904414:ios:fb41e326f922f085cc9acf',
    messagingSenderId: '347110904414',
    projectId: 'greentechfertilizer-b5cd0',
    databaseURL: 'https://greentechfertilizer-b5cd0-default-rtdb.firebaseio.com',
    storageBucket: 'greentechfertilizer-b5cd0.appspot.com',
    iosClientId: '347110904414-lbndchgu6uitf7v1jcklo6c08bda2d7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8eaMkb0ePV0rJnKLIogWNAmzsyr-9Boc',
    appId: '1:347110904414:ios:fb41e326f922f085cc9acf',
    messagingSenderId: '347110904414',
    projectId: 'greentechfertilizer-b5cd0',
    databaseURL: 'https://greentechfertilizer-b5cd0-default-rtdb.firebaseio.com',
    storageBucket: 'greentechfertilizer-b5cd0.appspot.com',
    iosClientId: '347110904414-lbndchgu6uitf7v1jcklo6c08bda2d7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhI8pQqT4w20q-x4bOnOl_4CMotYWaEqc',
    appId: '1:347110904414:web:cd100eee2f6211c4cc9acf',
    messagingSenderId: '347110904414',
    projectId: 'greentechfertilizer-b5cd0',
    authDomain: 'greentechfertilizer-b5cd0.firebaseapp.com',
    databaseURL: 'https://greentechfertilizer-b5cd0-default-rtdb.firebaseio.com',
    storageBucket: 'greentechfertilizer-b5cd0.appspot.com',
  );
}
